export const projectConstants = {
    NEW_PROJECT_REQUEST: 'NEW_PROJECT_REQUEST',
    NEW_PROJECT_SUCCESS: 'NEW_PROJECT_SUCCESS',
    NEW_PROJECT_FAILURE: 'NEW_PROJECT_FAILURE',

    FETCH_PROJECTS_REQUEST: 'FETCH_PROJECTS_REQUEST',
    FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
    FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_FAILURE',

    LOAD_PROJECT_REQUEST: 'LOAD_PROJECT_REQUEST',
    LOAD_PROJECT_SUCCESS: 'LOAD_PROJECT_SUCCESS',
    LOAD_PROJECT_FAILURE: 'LOAD_PROJECT_FAILURE',


    UPLOAD_PROJECT_REQUEST: 'UPLOAD_PROJECT_REQUEST',
    UPLOAD_PROJECT_SUCCESS: 'UPLOAD_PROJECT_SUCCESS',
    UPLOAD_PROJECT_FAILURE: 'UPLOAD_PROJECT_FAILURE',

    EXPORT_PROJECT_REQUEST: 'EXPORT_PROJECT_REQUEST',
    EXPORT_PROJECT_SUCCESS: 'EXPORT_PROJECT_SUCCESS',
    EXPORT_PROJECT_FAILURE: 'EXPORT_PROJECT_FAILURE',

    IMPORT_PROJECT_REQUEST: 'IMPORT_PROJECT_REQUEST',
    IMPORT_PROJECT_SUCCESS: 'IMPORT_PROJECT_SUCCESS',
    IMPORT_PROJECT_FAILURE: 'IMPORT_PROJECT_FAILURE'
};
